version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# .goreleaser.yaml
nfpms:
  # note that this is an array of nfpm configs
  - #
    id: vapour

    # Name of the package.
    #
    # Default: ProjectName.
    # Templates: allowed.
    package_name: vapour

    # Your app's vendor.
    vendor: Vapour

    # Your app's homepage.
    #
    # Default: inferred from global metadata.
    homepage: https://vapour.run

    # Your app's maintainer (probably you).
    #
    # Default: inferred from global metadata.
    maintainer: John Coene <jcoenep@gmail.com>

    # Your app's description.
    #
    # Default: inferred from global metadata.
    description: |-
      Vapour is a typed superset of R.

    # Your app's license.
    #
    # Default: inferred from global metadata.
    license: Apache 2.0

    # Formats to be generated.
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux

    # Umask to be used on files without explicit mode set. (overridable)
    #
    # Default: 0o002 (will remove world-writable permissions).
    umask: 0o002

    # Path that the binaries should be installed.
    #
    # Default: '/usr/bin'.
    bindir: /usr/bin

    # Version Release.
    release: 1

    # Section.
    section: default

    # Makes a meta package - an empty package that contains only supporting
    # files and dependencies.
    # When set to `true`, the `builds` option is ignored.
    meta: true
